### ISSUE TITLE
Interested in a Rust CfWorker-based implementation?

### ISSUE THREAD

**Issue by danya02** [GoldenStack/dayssincelastrustmcserver#5]
[Someone on your Reddit post](https://www.reddit.com/r/rust/comments/1fflzd2/comment/lmvrhu8/) suggested that this app should be written in Rust itself. I'm here to provide.

I made a demo of using Yew's server-side rendering with Cloudflare Workers: https://github.com/danya02/yew-ssr-wrangler-demo is the repo and https://yew-ssr-wrangler-demo.danya02.workers.dev/ is the live demo.

Since your app is so simple, it would be pretty straightforward to reimplement it using that. One advantage of doing that is that the server would be sending HTML, so it would be viewable by clients that don't understand JS (such as search engine crawlers). Of course, the more compelling reason is that it'll be written in Rust 🦀🦀🦀

A potential downside is that Cloudflare Workers have a request limit of 100k requests per day if you wanna stay on the free plan, vs CfPages which has unlimited clients, however I doubt that this would be an issue in practice.

If you would be interested in this, but don't wanna do it yourself, I can submit a PR with an implementation.

**Comment by GoldenStack** [comment]
Hi,
I could give a complicated explanation for why I wouldn't accept a Rust implementation of it, but the real reason is just because it works currently and I don't feel like it would be worth the nonzero hassle to get it switched over, even if it were someone else writing all of the code.

Sorry if this seems like a bad response, but I spent less than a day on this project and don't think it would be worth the effort.

Thank you for the offer, though! :rocket: :rocket: :rocket: :crab: :crab: :crab:
